name: Remote Desktop on GitHub Actions

on:
  workflow_dispatch: # ده بيسمحلك تشغل الـ workflow يدويًا من صفحة GitHub Actions

jobs:
  remote-desktop:
    runs-on: ubuntu-latest # بنستخدم أحدث نسخة من Ubuntu

    env:
      CRD_SSH_CODE: ${{ secrets.CODE }} # ده المتغير السري اللي هيكون فيه كود CRD
      USERNAME: user
      PASSWORD: root
      PIN: 123456

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # بيعمل checkout لمستودعك (لو فيه ملفات تانية محتاجها)

    - name: Setup Remote Desktop Environment
      run: |
        # تحديث النظام وتثبيت المتطلبات الأساسية
        sudo apt update
        sudo apt install -y curl wget xvfb xfce4 desktop-base xfce4-terminal xscreensaver xfce4-screensaver

        # تثبيت Google Chrome Remote Desktop
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg --install chrome-remote-desktop_current_amd64.deb || sudo apt install --assume-yes --fix-broken -y

        # تثبيت Google Chrome
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg --install google-chrome-stable_current_amd64.deb || sudo apt install --assume-yes --fix-broken -y

        # تثبيت Telegram Desktop
        sudo apt install -y telegram-desktop

        # تثبيت qBittorrent
        sudo apt install -y qbittorrent

        # إعداد XFCE4 كبيئة سطح مكتب لـ CRD
        echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" | sudo tee /etc/chrome-remote-desktop-session > /dev/null
        sudo systemctl disable lightdm.service

        # إنشاء المستخدم وتعيين كلمة المرور
        sudo useradd -m ${USERNAME}
        sudo adduser ${USERNAME} sudo
        echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
        sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd

        # إضافة المستخدم لـ chrome-remote-desktop group
        sudo adduser ${USERNAME} chrome-remote-desktop

        # إعداد CRD باستخدام الكود السري والـ PIN
        # لازم تشغل الأمر ده كمستخدم ${USERNAME} عشان يتم حفظ الإعدادات صحيحة
        # هذا الجزء تحدي كبير في GitHub Actions لأن ${CRD_SSH_CODE} عادةً ما يكون TOKEN طويل جدًا ويحتوي على مسافات
        # وقد لا يعمل مباشرة مع 'su -c'. قد تحتاج لاستخدام ملف مؤقت أو طرق أخرى لتمرير الكود بأمان.
        # الطريقة الأمثل هي:
        # 1. تشغيل CRD بالتوكن
        # 2. بدء الخدمة
        # 3. ابقاء الـ Job شغال

        # محاولة تنفيذ أمر CRD الأساسي
        # الطريقة دي ممكن تحتاج تعديل بناءً على كيفية توقع CRD للتوكن
        echo "${CRD_SSH_CODE}" | /opt/google/chrome-remote-desktop/start-chrome-remote-desktop --code-url="unused" --redirect-url="unused" --pin=${PIN}

        # بدء خدمة Chrome Remote Desktop (مهم جداً)
        sudo service chrome-remote-desktop start

        echo "Chrome Remote Desktop should now be running. You can connect using the specified PIN and user/pass."
        echo "Remember, this session will terminate after max 6 hours or when the workflow step finishes."
        echo "Log in PIN : ${PIN}"
        echo "User Name : ${USERNAME}"
        echo "User Pass : ${PASSWORD}"

        # ابقاء الـ Job شغال عشان CRD يستمر في العمل
        # هيفضل شغال لحد ما الـ job يوصل لأقصى مدة (6 ساعات)
        echo "Keeping the job alive for maximum duration..."
        sleep 21600 # 6 ساعات * 60 دقيقة * 60 ثانية
